/** @jsxRuntime automatic */
/** @jsxImportSource hono/jsx */
import { Layout } from '../components/Layout.jsx'

export const TermsOfServiceView = () => {
  return (
    <Layout title="Terms of Service | ToolStaq" description="ToolStaq Terms of Service and Disclaimers.">
      <div class="container" style="padding-top: var(--space-32); padding-bottom: var(--space-48);">
        <div class="workspace-panel">
          <h1 style="margin-bottom: var(--space-24);">Terms of Service</h1>
          <div style="line-height: 1.8;">
             <p><strong>Effective Date: {new Date().toLocaleDateString()}</strong></p>
             <h2 style="margin-top: var(--space-24);">1. Acceptance of Terms</h2>
             <p>By accessing and using ToolStaq.online ("the Service"), you accept and agree to be bound by the terms and provision of this agreement. If you do not agree to abide by the above, please do not use this service.</p>
             
             <h2 style="margin-top: var(--space-24);">2. Disclaimer of Warranties</h2>
             <p>The Service is provided on an "AS IS" and "AS AVAILABLE" basis. ToolStaq makes no warranties, expressed or implied, and hereby disclaims and negates all other warranties including, without limitation, implied warranties or conditions of merchantability, fitness for a particular purpose, or non-infringement of intellectual property or other violation of rights.</p>
             <p>While we strive for accuracy in our tools (e.g., parsers, formatters, calculators), we do not guarantee the absolute correctness of any output generated by the Service. You are solely responsible for verifying the accuracy of the output before using it in production environments.</p>
             
             <h2 style="margin-top: var(--space-24);">3. Limitation of Liability</h2>
             <p>In no event shall ToolStaq or its suppliers be liable for any damages (including, without limitation, damages for loss of data or profit, or due to business interruption) arising out of the use or inability to use the materials on the Service.</p>
          </div>
        </div>
      </div>
    </Layout>
  )
}
